apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod-shoppingapp
  name: shoppingclient-deployment
  labels:
    app: shoppingclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
        - name: shoppingclient
          image: proddevops.azurecr.io/shopping_client/shoppingclient:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: shoppingapi-configmap
                    key: shoppingapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  namespace: prod-shoppingapp 
  name: shoppingclient-service
spec:
  type: LoadBalancer
  selector:
    app: shoppingclient
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80