apiVersion : apps/v1
kind: Deployment
metadata:
  name: mongodbmongo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbmongo
  template:
    metadata:
      labels:
        app: mongodbmongo 
    spec:
      containers:
        - name: mongodbmongo 
          image: proddevops.azurecr.io/mongodbmongo
          ports:
          - containerPort: 27017